/**
 * Crazy Colors 40-Level Championship Campaign
 * Progressive difficulty from Hard (Level 1) to Final Challenge (Level 40).
 * Every level features finite obstacles, diverse geometry, rotation parameters, and star ratings.
 */

import { LevelDefinition, CrazyColor, ShapeType } from './types';

export const CRAZY_COLORS_LEVELS: LevelDefinition[] = [
  // -------------------------------------------------------------------------
  // TIER 1: HARD (LEVELS 1 - 5) - High initial challenge requiring true timing
  // -------------------------------------------------------------------------
  {
    id: 1,
    title: 'Diamond Gateway',
    difficulty: 'hard',
    description: 'Time your bounces through 3 rotating diamond squares with distinct colored segments.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'rotated_square', rotationSpeed: 1.35, scale: 1.0 },
      { shapeType: 'rotated_square', rotationSpeed: -1.45, scale: 1.0 },
      { shapeType: 'rotated_square', rotationSpeed: 1.55, scale: 1.0 },
    ],
    starThresholds: [200, 350, 500, 650, 800],
  },
  {
    id: 2,
    title: 'Open U-Corridor',
    difficulty: 'hard',
    description: 'Pass through 3 open U-shapes rotating with offset phases.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'u_shape', rotationSpeed: 1.4, scale: 1.05 },
      { shapeType: 'open_square', rotationSpeed: -1.5, scale: 1.05 },
      { shapeType: 'u_shape', rotationSpeed: 1.6, scale: 1.05 },
    ],
    starThresholds: [250, 400, 550, 750, 900],
  },
  {
    id: 3,
    title: 'Neon Chevrons',
    difficulty: 'hard',
    description: 'Clear through high-tension angled V-shaped chevrons.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'v_shape', rotationSpeed: 1.45, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -1.5, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 1.6, scale: 1.0 },
    ],
    starThresholds: [250, 420, 600, 800, 950],
  },
  {
    id: 4,
    title: 'Chromatic Ring',
    difficulty: 'hard',
    description: 'Navigate through circular 4-arc neon rings rotating clockwise and counter-clockwise.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'circle_ring', rotationSpeed: 1.5, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -1.6, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: 1.7, scale: 1.05 },
    ],
    starThresholds: [300, 500, 700, 900, 1100],
  },
  {
    id: 5,
    title: 'Delta Triangles',
    difficulty: 'hard',
    description: 'Equilateral triangles rotate with acute timing windows.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'triangle', rotationSpeed: 1.55, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -1.65, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: 1.75, scale: 1.0 },
      { shapeType: 'rotated_square', rotationSpeed: -1.6, scale: 1.0 },
    ],
    starThresholds: [350, 600, 850, 1100, 1300],
  },

  // -------------------------------------------------------------------------
  // TIER 2: VERY HARD (LEVELS 6 - 10)
  // -------------------------------------------------------------------------
  {
    id: 6,
    title: 'Rectangular Vault',
    difficulty: 'very_hard',
    description: 'Elongated rectangular gates rotate with varying speed.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'rectangle', rotationSpeed: 1.6, scale: 1.0 },
      { shapeType: 'u_shape', rotationSpeed: -1.7, scale: 1.0 },
      { shapeType: 'rectangle', rotationSpeed: 1.8, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: -1.75, scale: 1.0 },
    ],
    starThresholds: [400, 700, 950, 1200, 1450],
  },
  {
    id: 7,
    title: 'Inverted Chevrons',
    difficulty: 'very_hard',
    description: 'Sharp inverted V obstacles with tighter entry clearances.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'inverted_v', rotationSpeed: 1.7, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -1.75, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: 1.8, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -1.85, scale: 1.0 },
    ],
    starThresholds: [420, 720, 1000, 1250, 1500],
  },
  {
    id: 8,
    title: 'Curved C-Locks',
    difficulty: 'very_hard',
    description: 'Open C-shapes rotating with sudden directional shifts.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'c_shape', rotationSpeed: 1.75, scale: 1.05 },
      { shapeType: 'triangle', rotationSpeed: -1.8, scale: 1.0 },
      { shapeType: 'c_shape', rotationSpeed: 1.85, scale: 1.05 },
      { shapeType: 'rotated_square', rotationSpeed: -1.9, scale: 1.0 },
    ],
    starThresholds: [450, 750, 1050, 1300, 1550],
  },
  {
    id: 9,
    title: 'Neon Crossfire',
    difficulty: 'very_hard',
    description: 'Cross obstacles with 4 radiant colored arms spinning across the lane.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'cross', rotationSpeed: 1.8, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -1.85, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 1.9, scale: 1.05 },
      { shapeType: 'rectangle', rotationSpeed: -1.85, scale: 1.0 },
    ],
    starThresholds: [480, 800, 1100, 1400, 1650],
  },
  {
    id: 10,
    title: 'Concentric Rings',
    difficulty: 'very_hard',
    description: 'Double concentric rings spinning in opposite directions simultaneously!',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 1.75, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: -1.85, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: 1.9, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -1.95, scale: 1.0 },
    ],
    starThresholds: [500, 850, 1200, 1500, 1800],
  },

  // -------------------------------------------------------------------------
  // TIER 3: VERY HARD+ (LEVELS 11 - 15)
  // -------------------------------------------------------------------------
  {
    id: 11,
    title: 'Hexagonal Prism',
    difficulty: 'very_hard+',
    description: '6-segment hexagonal barriers with rapid color rotation.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'hexagon', rotationSpeed: 1.85, scale: 1.05 },
      { shapeType: 'triangle', rotationSpeed: -1.9, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 1.95, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -2.0, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 2.05, scale: 1.05 },
    ],
    starThresholds: [550, 950, 1300, 1650, 1950],
  },
  {
    id: 12,
    title: 'Dual Nested Squares',
    difficulty: 'very_hard+',
    description: 'Nested inner and outer squares rotating with phase shifts.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'concentric_square', rotationSpeed: 1.85, scale: 1.0 },
      { shapeType: 'u_shape', rotationSpeed: -1.95, scale: 1.05 },
      { shapeType: 'concentric_square', rotationSpeed: 2.0, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -2.05, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: 2.1, scale: 1.0 },
    ],
    starThresholds: [600, 1000, 1400, 1750, 2100],
  },
  {
    id: 13,
    title: 'Star Polygons',
    difficulty: 'very_hard+',
    description: '8-pointed star polygons with serrated neon perimeter segments.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'star_polygon', rotationSpeed: 1.9, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -2.0, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 2.05, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: -2.1, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 2.15, scale: 1.0 },
    ],
    starThresholds: [650, 1100, 1500, 1850, 2250],
  },
  {
    id: 14,
    title: 'Swaying Crossway',
    difficulty: 'very_hard+',
    description: 'Obstacles oscillate horizontally while rotating.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'circle_ring', rotationSpeed: 1.95, scale: 1.0, oscillationX: { amplitude: 35, speed: 1.8 } },
      { shapeType: 'rotated_square', rotationSpeed: -2.05, scale: 1.0, oscillationX: { amplitude: 30, speed: 2.0 } },
      { shapeType: 'double_ring', rotationSpeed: 2.1, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -2.15, scale: 1.0, oscillationX: { amplitude: 35, speed: 2.2 } },
      { shapeType: 'hexagon', rotationSpeed: 2.2, scale: 1.05 },
    ],
    starThresholds: [700, 1150, 1600, 2000, 2400],
  },
  {
    id: 15,
    title: 'Chamber of Trials',
    difficulty: 'very_hard+',
    description: 'Five distinct geometric obstacles in rapid continuous succession.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'triangle', rotationSpeed: 2.0, scale: 1.0 },
      { shapeType: 'open_square', rotationSpeed: -2.1, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: 2.15, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -2.2, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 2.25, scale: 1.0 },
    ],
    starThresholds: [750, 1250, 1700, 2150, 2550],
  },

  // -------------------------------------------------------------------------
  // TIER 4: EXPERT (LEVELS 16 - 20)
  // -------------------------------------------------------------------------
  {
    id: 16,
    title: 'Velocity Diamonds',
    difficulty: 'expert',
    description: 'High-speed diamond gates with tight color clearance.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'diamond', rotationSpeed: 2.2, scale: 1.0 },
      { shapeType: 'rectangle', rotationSpeed: -2.3, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: 2.35, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -2.4, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: 2.45, scale: 1.0 },
    ],
    starThresholds: [800, 1350, 1850, 2300, 2700],
  },
  {
    id: 17,
    title: 'Twin Vortex',
    difficulty: 'expert',
    description: 'Dual double-ring vortexes paired with sharp chevrons.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 2.25, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -2.35, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 2.4, scale: 1.0 },
      { shapeType: 'c_shape', rotationSpeed: -2.45, scale: 1.05 },
      { shapeType: 'hexagon', rotationSpeed: 2.5, scale: 1.05 },
    ],
    starThresholds: [850, 1400, 1950, 2450, 2850],
  },
  {
    id: 18,
    title: 'Hexa-Star Matrix',
    difficulty: 'expert',
    description: 'Alternating hexagons and star polygons spinning at breakneck velocity.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'hexagon', rotationSpeed: 2.3, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: -2.4, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 2.45, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: -2.5, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: 2.55, scale: 1.0 },
    ],
    starThresholds: [900, 1500, 2050, 2550, 3000],
  },
  {
    id: 19,
    title: 'Acute Precision',
    difficulty: 'expert',
    description: 'Acute triangles and inverted chevrons with oscillating drift.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'triangle', rotationSpeed: 2.35, scale: 1.0, oscillationX: { amplitude: 35, speed: 2.0 } },
      { shapeType: 'inverted_v', rotationSpeed: -2.45, scale: 1.0, oscillationX: { amplitude: 35, speed: 2.2 } },
      { shapeType: 'concentric_square', rotationSpeed: 2.5, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -2.55, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: 2.6, scale: 1.0 },
    ],
    starThresholds: [950, 1550, 2150, 2650, 3150],
  },
  {
    id: 20,
    title: 'Crossfire Gauntlet',
    difficulty: 'expert',
    description: 'Fast spinning crosses combined with nested geometric boxes.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'cross', rotationSpeed: 2.4, scale: 1.05 },
      { shapeType: 'concentric_square', rotationSpeed: -2.5, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 2.55, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: -2.6, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 2.65, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: -2.7, scale: 1.0 },
    ],
    starThresholds: [1000, 1650, 2250, 2800, 3300],
  },

  // -------------------------------------------------------------------------
  // TIER 5: EXPERT+ (LEVELS 21 - 25)
  // -------------------------------------------------------------------------
  {
    id: 21,
    title: 'Cyclone Arcs',
    difficulty: 'expert+',
    description: 'High-speed circle rings paired with oscillating chevron bars.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'circle_ring', rotationSpeed: 2.5, scale: 1.05 },
      { shapeType: 'v_shape', rotationSpeed: -2.6, scale: 1.0, oscillationX: { amplitude: 40, speed: 2.4 } },
      { shapeType: 'circle_ring', rotationSpeed: 2.65, scale: 1.05 },
      { shapeType: 'inverted_v', rotationSpeed: -2.7, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: 2.75, scale: 1.0 },
      { shapeType: 'rectangle', rotationSpeed: -2.8, scale: 1.0 },
    ],
    starThresholds: [1100, 1750, 2400, 2950, 3500],
  },
  {
    id: 22,
    title: 'Dual Ring Orbit',
    difficulty: 'expert+',
    description: 'Back-to-back double ring chambers with counter-rotating speed.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 2.55, scale: 1.0 },
      { shapeType: 'open_square', rotationSpeed: -2.65, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 2.7, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -2.75, scale: 1.05 },
      { shapeType: 'hexagon', rotationSpeed: 2.8, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: -2.85, scale: 1.0 },
    ],
    starThresholds: [1150, 1850, 2500, 3100, 3650],
  },
  {
    id: 23,
    title: 'Swaying Starburst',
    difficulty: 'expert+',
    description: 'Star polygons swaying across the screen with synchronized diamonds.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'star_polygon', rotationSpeed: 2.6, scale: 1.0, oscillationX: { amplitude: 42, speed: 2.5 } },
      { shapeType: 'rotated_square', rotationSpeed: -2.7, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 2.75, scale: 1.0, oscillationX: { amplitude: 42, speed: 2.5 } },
      { shapeType: 'concentric_square', rotationSpeed: -2.8, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: 2.85, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: -2.9, scale: 1.0 },
    ],
    starThresholds: [1200, 1950, 2600, 3250, 3800],
  },
  {
    id: 24,
    title: 'Hexa-Cross Nexus',
    difficulty: 'expert+',
    description: 'Hexagons and 4-way crosses forming a dense gauntlet.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'cross', rotationSpeed: 2.65, scale: 1.05 },
      { shapeType: 'hexagon', rotationSpeed: -2.75, scale: 1.05 },
      { shapeType: 'cross', rotationSpeed: 2.8, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: -2.85, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 2.9, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -2.95, scale: 1.0 },
    ],
    starThresholds: [1250, 2050, 2750, 3400, 3950],
  },
  {
    id: 25,
    title: 'Inverted Labyrinth',
    difficulty: 'expert+',
    description: 'Six varied obstacles with inverted chevrons and nested boxes.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'inverted_v', rotationSpeed: 2.7, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: -2.8, scale: 1.0 },
      { shapeType: 'u_shape', rotationSpeed: 2.85, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: -2.9, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: 2.95, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.0, scale: 1.05 },
    ],
    starThresholds: [1300, 2150, 2850, 3500, 4100],
  },

  // -------------------------------------------------------------------------
  // TIER 6: EXTREME (LEVELS 26 - 30)
  // -------------------------------------------------------------------------
  {
    id: 26,
    title: 'Velocity Surge',
    difficulty: 'extreme',
    description: 'Blazing speed rotation with tight reflex requirements.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'rotated_square', rotationSpeed: 2.8, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -2.9, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: 2.95, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: -3.0, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: 3.05, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.1, scale: 1.05 },
    ],
    starThresholds: [1400, 2250, 3000, 3700, 4300],
  },
  {
    id: 27,
    title: 'Triple Vortex Nexus',
    difficulty: 'extreme',
    description: 'Double concentric rings interspersed with high-speed chevrons.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 2.85, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -2.95, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.0, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: -3.05, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: 3.1, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: -3.15, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: 3.2, scale: 1.0 },
    ],
    starThresholds: [1500, 2400, 3200, 3900, 4550],
  },
  {
    id: 28,
    title: 'Serrated Stars',
    difficulty: 'extreme',
    description: 'Serrated star polygons moving in fast harmonic oscillation.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'star_polygon', rotationSpeed: 2.9, scale: 1.0, oscillationX: { amplitude: 44, speed: 2.6 } },
      { shapeType: 'hexagon', rotationSpeed: -3.0, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: 3.05, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -3.1, scale: 1.0, oscillationX: { amplitude: 44, speed: 2.6 } },
      { shapeType: 'inverted_v', rotationSpeed: 3.15, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -3.2, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.25, scale: 1.05 },
    ],
    starThresholds: [1600, 2550, 3400, 4100, 4800],
  },
  {
    id: 29,
    title: 'Boxed Matrix',
    difficulty: 'extreme',
    description: 'Nested boxes and sharp diamonds shifting with narrow clear points.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'concentric_square', rotationSpeed: 2.95, scale: 1.0 },
      { shapeType: 'open_square', rotationSpeed: -3.05, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: 3.1, scale: 1.0 },
      { shapeType: 'u_shape', rotationSpeed: -3.15, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 3.2, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: -3.25, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: 3.3, scale: 1.0 },
    ],
    starThresholds: [1700, 2700, 3600, 4300, 5050],
  },
  {
    id: 30,
    title: 'Super-Speed Octagon',
    difficulty: 'extreme',
    description: '7 dynamic obstacles rotating at extreme speed. Stay centered!',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'circle_ring', rotationSpeed: 3.0, scale: 1.05 },
      { shapeType: 'triangle', rotationSpeed: -3.1, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 3.15, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.2, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 3.25, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -3.3, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: 3.35, scale: 1.0 },
    ],
    starThresholds: [1800, 2850, 3800, 4550, 5300],
  },

  // -------------------------------------------------------------------------
  // TIER 7: MASTER (LEVELS 31 - 35)
  // -------------------------------------------------------------------------
  {
    id: 31,
    title: 'Master Convergence',
    difficulty: 'master',
    description: 'Fast multi-shape convergence with high-frequency oscillation.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'rotated_square', rotationSpeed: 3.1, scale: 1.0, oscillationX: { amplitude: 45, speed: 2.7 } },
      { shapeType: 'circle_ring', rotationSpeed: -3.2, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 3.25, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -3.3, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 3.35, scale: 1.05 },
      { shapeType: 'cross', rotationSpeed: -3.4, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: 3.45, scale: 1.0 },
    ],
    starThresholds: [1900, 3000, 4000, 4800, 5600],
  },
  {
    id: 32,
    title: 'Vortex Inversion',
    difficulty: 'master',
    description: 'Concentric boxes and double rings testing your rhythm under pressure.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'concentric_square', rotationSpeed: 3.15, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: -3.25, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 3.3, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -3.35, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: 3.4, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: -3.45, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: 3.5, scale: 1.05 },
    ],
    starThresholds: [2000, 3150, 4200, 5050, 5900],
  },
  {
    id: 33,
    title: 'Hexa-Chromatic Marathon',
    difficulty: 'master',
    description: 'Seven rapid-fire obstacles in relentless succession.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'hexagon', rotationSpeed: 3.2, scale: 1.05 },
      { shapeType: 'cross', rotationSpeed: -3.3, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 3.35, scale: 1.0 },
      { shapeType: 'open_square', rotationSpeed: -3.4, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: 3.45, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: -3.5, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: 3.55, scale: 1.05 },
    ],
    starThresholds: [2100, 3300, 4400, 5300, 6200],
  },
  {
    id: 34,
    title: 'Precision Gauntlet',
    difficulty: 'master',
    description: 'Acute angles with rapid directional switching.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'triangle', rotationSpeed: 3.25, scale: 1.0 },
      { shapeType: 'inverted_v', rotationSpeed: -3.35, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: 3.4, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: -3.45, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 3.5, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.55, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: 3.6, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: -3.65, scale: 1.05 },
    ],
    starThresholds: [2200, 3500, 4650, 5600, 6550],
  },
  {
    id: 35,
    title: 'Master Marathon',
    difficulty: 'master',
    description: 'Eight consecutive obstacles. Absolute focus required.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'circle_ring', rotationSpeed: 3.3, scale: 1.05 },
      { shapeType: 'concentric_square', rotationSpeed: -3.4, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 3.45, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: -3.5, scale: 1.0 },
      { shapeType: 'u_shape', rotationSpeed: 3.55, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: -3.6, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.65, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: -3.7, scale: 1.0 },
    ],
    starThresholds: [2350, 3700, 4900, 5900, 6900],
  },

  // -------------------------------------------------------------------------
  // TIER 8: MASTER+ (LEVELS 36 - 39)
  // -------------------------------------------------------------------------
  {
    id: 36,
    title: 'Sonic Rings',
    difficulty: 'master+',
    description: 'Super-fast concentric vortex rings with razor-thin safe windows.',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 3.4, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.5, scale: 1.05 },
      { shapeType: 'double_ring', rotationSpeed: 3.55, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -3.6, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: 3.65, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -3.7, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 3.75, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -3.8, scale: 1.05 },
    ],
    starThresholds: [2500, 3900, 5200, 6250, 7300],
  },
  {
    id: 37,
    title: 'Chevrons of Fire',
    difficulty: 'master+',
    description: 'Fast synchronized chevrons oscillating in opposite directions.',
    startColor: 'pink',
    obstacles: [
      { shapeType: 'v_shape', rotationSpeed: 3.45, scale: 1.0, oscillationX: { amplitude: 45, speed: 2.8 } },
      { shapeType: 'inverted_v', rotationSpeed: -3.55, scale: 1.0, oscillationX: { amplitude: 45, speed: 2.8 } },
      { shapeType: 'double_ring', rotationSpeed: 3.6, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -3.65, scale: 1.0 },
      { shapeType: 'concentric_square', rotationSpeed: 3.7, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: -3.75, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: 3.8, scale: 1.0 },
      { shapeType: 'circle_ring', rotationSpeed: -3.85, scale: 1.05 },
    ],
    starThresholds: [2650, 4100, 5500, 6600, 7700],
  },
  {
    id: 38,
    title: 'Hyper Harmonic Drift',
    difficulty: 'master+',
    description: 'Extreme harmonic horizontal drift on high-velocity shapes.',
    startColor: 'cyan',
    obstacles: [
      { shapeType: 'star_polygon', rotationSpeed: 3.5, scale: 1.0, oscillationX: { amplitude: 48, speed: 3.0 } },
      { shapeType: 'hexagon', rotationSpeed: -3.6, scale: 1.05, oscillationX: { amplitude: 40, speed: 2.8 } },
      { shapeType: 'double_ring', rotationSpeed: 3.65, scale: 1.0 },
      { shapeType: 'open_square', rotationSpeed: -3.7, scale: 1.05 },
      { shapeType: 'concentric_square', rotationSpeed: 3.75, scale: 1.0 },
      { shapeType: 'triangle', rotationSpeed: -3.8, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.85, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -3.9, scale: 1.05 },
    ],
    starThresholds: [2800, 4350, 5800, 7000, 8150],
  },
  {
    id: 39,
    title: 'Championship Gate',
    difficulty: 'master+',
    description: 'The penultimate gauntlet before the Grand Finale. Eight high-tier shapes.',
    startColor: 'yellow',
    obstacles: [
      { shapeType: 'concentric_square', rotationSpeed: 3.55, scale: 1.0 },
      { shapeType: 'double_ring', rotationSpeed: -3.65, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: 3.7, scale: 1.0 },
      { shapeType: 'star_polygon', rotationSpeed: -3.75, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.8, scale: 1.05 },
      { shapeType: 'hexagon', rotationSpeed: -3.85, scale: 1.05 },
      { shapeType: 'inverted_v', rotationSpeed: 3.9, scale: 1.0 },
      { shapeType: 'diamond', rotationSpeed: -3.95, scale: 1.0 },
    ],
    starThresholds: [3000, 4600, 6150, 7400, 8600],
  },

  // -------------------------------------------------------------------------
  // TIER 9: FINAL CHALLENGE (LEVEL 40 - THE ABSOLUTE PINNACLE)
  // -------------------------------------------------------------------------
  {
    id: 40,
    title: 'Crazy Colors Grandmaster',
    difficulty: 'final_challenge',
    description: 'The ultimate 9-obstacle championship course! Complete this to become the Crazy Colors Champion!',
    startColor: 'purple',
    obstacles: [
      { shapeType: 'double_ring', rotationSpeed: 3.6, scale: 1.05 },
      { shapeType: 'star_polygon', rotationSpeed: -3.7, scale: 1.0, oscillationX: { amplitude: 46, speed: 2.8 } },
      { shapeType: 'concentric_square', rotationSpeed: 3.75, scale: 1.0 },
      { shapeType: 'v_shape', rotationSpeed: -3.8, scale: 1.0 },
      { shapeType: 'cross', rotationSpeed: 3.85, scale: 1.05 },
      { shapeType: 'triangle', rotationSpeed: -3.9, scale: 1.0 },
      { shapeType: 'hexagon', rotationSpeed: 3.95, scale: 1.05 },
      { shapeType: 'circle_ring', rotationSpeed: -4.0, scale: 1.05 },
      { shapeType: 'diamond', rotationSpeed: 4.05, scale: 1.0 },
    ],
    starThresholds: [3300, 5000, 6700, 8100, 9500],
  },
];
