/**
 * Puzzle Block 40-Level Campaign Configuration
 * Exactly 40 Levels. Level 1 unlocked, 2-40 locked.
 * Levels 1-5: Hard (initial block layouts, tight spaces, strategic placement required).
 * Levels 6-10: Hard+
 * Levels 11-15: Very Hard (Wood blockers)
 * Levels 16-20: Expert (Ice & Stone blockers)
 * Levels 21-25: Expert+ (Special bomb & line clears, locked cells)
 * Levels 26-30: Extreme
 * Levels 31-35: Master
 * Levels 36-39: Master+
 * Level 40: Master+ Final Grand Challenge
 */

import { LevelDefinition } from './types';

export const PUZZLE_BLOCK_LEVELS: LevelDefinition[] = [
  // ===================== LEVELS 1 - 5: HARD =====================
  {
    id: 1,
    title: 'Crossroad Gauntlet',
    difficulty: 'hard',
    targetScore: 1200,
    targetLines: 5,
    description: 'A pre-filled crossroad grid leaves tight corridors. Plan multi-line clearing to survive!',
    reshuffleLimit: 2,
    starThresholds: [1200, 1800, 2500],
    initialBoard: [
      // Pre-placed blocks creating tight corridors
      { row: 2, col: 2, color: 'cyan' },
      { row: 2, col: 3, color: 'cyan' },
      { row: 3, col: 2, color: 'cyan' },
      { row: 7, col: 7, color: 'magenta' },
      { row: 7, col: 8, color: 'magenta' },
      { row: 8, col: 7, color: 'magenta' },
      { row: 5, col: 4, color: 'orange' },
      { row: 5, col: 5, color: 'orange' },
      { row: 4, col: 5, color: 'green' },
      { row: 9, col: 1, color: 'purple' },
      { row: 9, col: 2, color: 'purple' },
      { row: 9, col: 3, color: 'purple' },
      { row: 0, col: 6, color: 'yellow' },
      { row: 0, col: 7, color: 'yellow' },
    ],
  },
  {
    id: 2,
    title: 'Twin Pillars',
    difficulty: 'hard',
    targetScore: 1600,
    targetLines: 7,
    description: 'Vertical pillars divide the board. Form horizontal bridges to collapse columns.',
    reshuffleLimit: 2,
    starThresholds: [1600, 2400, 3200],
    initialBoard: [
      { row: 1, col: 3, color: 'purple' },
      { row: 2, col: 3, color: 'purple' },
      { row: 3, col: 3, color: 'purple' },
      { row: 6, col: 6, color: 'cyan' },
      { row: 7, col: 6, color: 'cyan' },
      { row: 8, col: 6, color: 'cyan' },
      { row: 4, col: 0, color: 'magenta' },
      { row: 4, col: 1, color: 'magenta' },
      { row: 4, col: 8, color: 'green' },
      { row: 4, col: 9, color: 'green' },
    ],
  },
  {
    id: 3,
    title: 'Checker Labyrinth',
    difficulty: 'hard',
    targetScore: 2000,
    targetLines: 8,
    description: 'Staggered clusters restrict 3x3 drops. Clear channels before you run out of moves.',
    reshuffleLimit: 2,
    starThresholds: [2000, 3000, 4000],
    initialBoard: [
      { row: 1, col: 1, color: 'orange' },
      { row: 1, col: 8, color: 'orange' },
      { row: 8, col: 1, color: 'orange' },
      { row: 8, col: 8, color: 'orange' },
      { row: 4, col: 4, color: 'yellow' },
      { row: 4, col: 5, color: 'yellow' },
      { row: 5, col: 4, color: 'yellow' },
      { row: 5, col: 5, color: 'yellow' },
    ],
  },
  {
    id: 4,
    title: 'Corner Squeeze',
    difficulty: 'hard',
    targetScore: 2400,
    targetLines: 10,
    description: 'Heavily occupied corner quadrants. Focus on center combos to score big.',
    reshuffleLimit: 2,
    starThresholds: [2400, 3400, 4500],
    initialBoard: [
      { row: 0, col: 0, color: 'magenta' },
      { row: 0, col: 1, color: 'magenta' },
      { row: 1, col: 0, color: 'magenta' },
      { row: 0, col: 8, color: 'green' },
      { row: 0, col: 9, color: 'green' },
      { row: 1, col: 9, color: 'green' },
      { row: 8, col: 0, color: 'cyan' },
      { row: 9, col: 0, color: 'cyan' },
      { row: 9, col: 1, color: 'cyan' },
      { row: 9, col: 8, color: 'purple' },
      { row: 9, col: 9, color: 'purple' },
      { row: 8, col: 9, color: 'purple' },
    ],
  },
  {
    id: 5,
    title: 'The Fortress Wall',
    difficulty: 'hard',
    targetScore: 2800,
    targetLines: 12,
    description: 'A staggered perimeter wall blocks standard polyomino drops.',
    reshuffleLimit: 2,
    starThresholds: [2800, 4000, 5200],
    initialBoard: [
      { row: 3, col: 2, color: 'orange' },
      { row: 3, col: 3, color: 'orange' },
      { row: 3, col: 6, color: 'orange' },
      { row: 3, col: 7, color: 'orange' },
      { row: 6, col: 2, color: 'yellow' },
      { row: 6, col: 3, color: 'yellow' },
      { row: 6, col: 6, color: 'yellow' },
      { row: 6, col: 7, color: 'yellow' },
      { row: 4, col: 4, color: 'magenta' },
      { row: 5, col: 5, color: 'cyan' },
    ],
  },

  // ===================== LEVELS 6 - 10: HARD+ =====================
  {
    id: 6,
    title: 'Chevron Ridge',
    difficulty: 'hard+',
    targetScore: 3200,
    targetLines: 14,
    description: 'Diagonal chevron lines obstruct corner-to-corner flow.',
    reshuffleLimit: 2,
    starThresholds: [3200, 4500, 6000],
    initialBoard: [
      { row: 2, col: 2, color: 'green' },
      { row: 3, col: 3, color: 'green' },
      { row: 4, col: 4, color: 'green' },
      { row: 5, col: 5, color: 'cyan' },
      { row: 6, col: 6, color: 'cyan' },
      { row: 7, col: 7, color: 'cyan' },
    ],
  },
  {
    id: 7,
    title: 'Split Horizons',
    difficulty: 'hard+',
    targetScore: 3600,
    targetLines: 15,
    description: 'Two staggered horizontal barriers force vertical row alignment.',
    reshuffleLimit: 2,
    starThresholds: [3600, 5000, 6800],
    initialBoard: [
      { row: 3, col: 1, color: 'magenta' },
      { row: 3, col: 2, color: 'magenta' },
      { row: 3, col: 3, color: 'magenta' },
      { row: 3, col: 6, color: 'orange' },
      { row: 3, col: 7, color: 'orange' },
      { row: 3, col: 8, color: 'orange' },
      { row: 6, col: 2, color: 'purple' },
      { row: 6, col: 3, color: 'purple' },
      { row: 6, col: 4, color: 'purple' },
      { row: 6, col: 7, color: 'yellow' },
    ],
  },
  {
    id: 8,
    title: 'Diamond Bastion',
    difficulty: 'hard+',
    targetScore: 4000,
    targetLines: 16,
    description: 'Diamond perimeter in center quadrant. Clear outward from the middle.',
    reshuffleLimit: 2,
    starThresholds: [4000, 5600, 7500],
    initialBoard: [
      { row: 2, col: 4, color: 'yellow' },
      { row: 2, col: 5, color: 'yellow' },
      { row: 4, col: 2, color: 'cyan' },
      { row: 5, col: 2, color: 'cyan' },
      { row: 4, col: 7, color: 'green' },
      { row: 5, col: 7, color: 'green' },
      { row: 7, col: 4, color: 'purple' },
      { row: 7, col: 5, color: 'purple' },
    ],
  },
  {
    id: 9,
    title: 'The Trident',
    difficulty: 'hard+',
    targetScore: 4500,
    targetLines: 18,
    description: 'Three vertical prongs split the board into narrow slots.',
    reshuffleLimit: 2,
    starThresholds: [4500, 6200, 8200],
    initialBoard: [
      { row: 1, col: 2, color: 'orange' },
      { row: 2, col: 2, color: 'orange' },
      { row: 3, col: 2, color: 'orange' },
      { row: 1, col: 5, color: 'magenta' },
      { row: 2, col: 5, color: 'magenta' },
      { row: 3, col: 5, color: 'magenta' },
      { row: 1, col: 7, color: 'cyan' },
      { row: 2, col: 7, color: 'cyan' },
      { row: 3, col: 7, color: 'cyan' },
      { row: 7, col: 4, color: 'yellow' },
      { row: 8, col: 4, color: 'yellow' },
    ],
  },
  {
    id: 10,
    title: 'Iron Perimeter',
    difficulty: 'hard+',
    targetScore: 5000,
    targetLines: 20,
    description: 'Challenging boundary clusters. High accuracy needed for 3-star victory.',
    reshuffleLimit: 2,
    starThresholds: [5000, 7000, 9500],
    initialBoard: [
      { row: 0, col: 3, color: 'purple' },
      { row: 0, col: 4, color: 'purple' },
      { row: 0, col: 5, color: 'purple' },
      { row: 9, col: 4, color: 'cyan' },
      { row: 9, col: 5, color: 'cyan' },
      { row: 9, col: 6, color: 'cyan' },
      { row: 4, col: 0, color: 'green' },
      { row: 5, col: 0, color: 'green' },
      { row: 4, col: 9, color: 'magenta' },
      { row: 5, col: 9, color: 'magenta' },
    ],
  },

  // ===================== LEVELS 11 - 15: VERY HARD (WOOD BLOCKERS) =====================
  {
    id: 11,
    title: 'Timber Enclave',
    difficulty: 'very_hard',
    targetScore: 5500,
    targetLines: 20,
    targetBlockers: 4,
    description: 'Wood blockers introduced! Clear adjacent rows or columns to shatter them.',
    reshuffleLimit: 2,
    starThresholds: [5500, 7500, 10000],
    initialBoard: [
      { row: 3, col: 3, blocker: 'wood' },
      { row: 3, col: 6, blocker: 'wood' },
      { row: 6, col: 3, blocker: 'wood' },
      { row: 6, col: 6, blocker: 'wood' },
      { row: 1, col: 1, color: 'cyan' },
      { row: 8, col: 8, color: 'magenta' },
    ],
  },
  {
    id: 12,
    title: 'Cedar Barricade',
    difficulty: 'very_hard',
    targetScore: 6000,
    targetLines: 22,
    targetBlockers: 6,
    description: 'Six dense timber blocks flank the center. Multi-line clears shatter them faster.',
    reshuffleLimit: 2,
    starThresholds: [6000, 8200, 11000],
    initialBoard: [
      { row: 4, col: 2, blocker: 'wood' },
      { row: 4, col: 3, blocker: 'wood' },
      { row: 4, col: 6, blocker: 'wood' },
      { row: 4, col: 7, blocker: 'wood' },
      { row: 2, col: 5, blocker: 'wood' },
      { row: 7, col: 5, blocker: 'wood' },
    ],
  },
  {
    id: 13,
    title: 'Oak Crossroad',
    difficulty: 'very_hard',
    targetScore: 6500,
    targetLines: 24,
    targetBlockers: 8,
    description: 'An eight-block wood constellation. Clear both horizontal and vertical lines.',
    reshuffleLimit: 2,
    starThresholds: [6500, 9000, 12000],
    initialBoard: [
      { row: 2, col: 4, blocker: 'wood' },
      { row: 2, col: 5, blocker: 'wood' },
      { row: 4, col: 2, blocker: 'wood' },
      { row: 5, col: 2, blocker: 'wood' },
      { row: 4, col: 7, blocker: 'wood' },
      { row: 5, col: 7, blocker: 'wood' },
      { row: 7, col: 4, blocker: 'wood' },
      { row: 7, col: 5, blocker: 'wood' },
    ],
  },
  {
    id: 14,
    title: 'Dense Canopy',
    difficulty: 'very_hard',
    targetScore: 7000,
    targetLines: 25,
    targetBlockers: 8,
    description: 'Tight grid layout with alternating wood nodes. Preserve open space for large pieces.',
    reshuffleLimit: 2,
    starThresholds: [7000, 9800, 13000],
    initialBoard: [
      { row: 1, col: 4, blocker: 'wood' },
      { row: 1, col: 5, blocker: 'wood' },
      { row: 8, col: 4, blocker: 'wood' },
      { row: 8, col: 5, blocker: 'wood' },
      { row: 4, col: 1, blocker: 'wood' },
      { row: 5, col: 1, blocker: 'wood' },
      { row: 4, col: 8, blocker: 'wood' },
      { row: 5, col: 8, blocker: 'wood' },
      { row: 4, col: 4, color: 'purple' },
      { row: 5, col: 5, color: 'orange' },
    ],
  },
  {
    id: 15,
    title: 'Lumber Citadel',
    difficulty: 'very_hard',
    targetScore: 7500,
    targetLines: 26,
    targetBlockers: 10,
    description: 'Ten stubborn wood fortifications. Combos are mandatory to reach the target score.',
    reshuffleLimit: 2,
    starThresholds: [7500, 10500, 14000],
    initialBoard: [
      { row: 3, col: 2, blocker: 'wood' },
      { row: 3, col: 7, blocker: 'wood' },
      { row: 6, col: 2, blocker: 'wood' },
      { row: 6, col: 7, blocker: 'wood' },
      { row: 2, col: 4, blocker: 'wood' },
      { row: 2, col: 5, blocker: 'wood' },
      { row: 7, col: 4, blocker: 'wood' },
      { row: 7, col: 5, blocker: 'wood' },
      { row: 4, col: 4, blocker: 'wood' },
      { row: 5, col: 5, blocker: 'wood' },
    ],
  },

  // ===================== LEVELS 16 - 20: EXPERT (ICE & STONE) =====================
  {
    id: 16,
    title: 'Glacial Outpost',
    difficulty: 'expert',
    targetScore: 8000,
    targetLines: 28,
    targetBlockers: 6,
    description: 'Ice blocks require 2 adjacent line clears: crack first, then shatter completely!',
    reshuffleLimit: 2,
    starThresholds: [8000, 11200, 15000],
    initialBoard: [
      { row: 3, col: 3, blocker: 'ice' },
      { row: 3, col: 6, blocker: 'ice' },
      { row: 6, col: 3, blocker: 'ice' },
      { row: 6, col: 6, blocker: 'ice' },
      { row: 1, col: 5, blocker: 'stone' },
      { row: 8, col: 5, blocker: 'stone' },
    ],
  },
  {
    id: 17,
    title: 'Granite & Permafrost',
    difficulty: 'expert',
    targetScore: 8500,
    targetLines: 30,
    targetBlockers: 8,
    description: 'Indestructible stone obstacles mixed with cracked ice blocks.',
    reshuffleLimit: 2,
    starThresholds: [8500, 12000, 16000],
    initialBoard: [
      { row: 2, col: 2, blocker: 'stone' },
      { row: 2, col: 7, blocker: 'stone' },
      { row: 7, col: 2, blocker: 'stone' },
      { row: 7, col: 7, blocker: 'stone' },
      { row: 4, col: 3, blocker: 'ice' },
      { row: 4, col: 6, blocker: 'ice' },
      { row: 5, col: 3, blocker: 'ice' },
      { row: 5, col: 6, blocker: 'ice' },
    ],
  },
  {
    id: 18,
    title: 'Frozen Meridian',
    difficulty: 'expert',
    targetScore: 9000,
    targetLines: 32,
    targetBlockers: 8,
    description: 'A wall of frost divides the 10x10 board. Execute double-row clears to advance.',
    reshuffleLimit: 2,
    starThresholds: [9000, 12800, 17000],
    initialBoard: [
      { row: 4, col: 1, blocker: 'ice' },
      { row: 4, col: 2, blocker: 'ice' },
      { row: 4, col: 7, blocker: 'ice' },
      { row: 4, col: 8, blocker: 'ice' },
      { row: 5, col: 1, blocker: 'ice' },
      { row: 5, col: 2, blocker: 'ice' },
      { row: 5, col: 7, blocker: 'ice' },
      { row: 5, col: 8, blocker: 'ice' },
    ],
  },
  {
    id: 19,
    title: 'Cobalt Crags',
    difficulty: 'expert',
    targetScore: 9500,
    targetLines: 34,
    targetBlockers: 10,
    description: 'Chiseled stone clusters reduce available 4x1 and 5x1 placement pockets.',
    reshuffleLimit: 2,
    starThresholds: [9500, 13500, 18000],
    initialBoard: [
      { row: 1, col: 1, blocker: 'stone' },
      { row: 1, col: 8, blocker: 'stone' },
      { row: 8, col: 1, blocker: 'stone' },
      { row: 8, col: 8, blocker: 'stone' },
      { row: 3, col: 4, blocker: 'wood' },
      { row: 3, col: 5, blocker: 'wood' },
      { row: 6, col: 4, blocker: 'ice' },
      { row: 6, col: 5, blocker: 'ice' },
      { row: 4, col: 3, color: 'magenta' },
      { row: 5, col: 6, color: 'cyan' },
    ],
  },
  {
    id: 20,
    title: 'The Crystal Vault',
    difficulty: 'expert',
    targetScore: 10000,
    targetLines: 35,
    targetBlockers: 12,
    description: 'Twelve layered ice and wood fortifications. 10,000 point threshold.',
    reshuffleLimit: 2,
    starThresholds: [10000, 14200, 19000],
    initialBoard: [
      { row: 2, col: 3, blocker: 'ice' },
      { row: 2, col: 6, blocker: 'ice' },
      { row: 7, col: 3, blocker: 'ice' },
      { row: 7, col: 6, blocker: 'ice' },
      { row: 3, col: 4, blocker: 'wood' },
      { row: 3, col: 5, blocker: 'wood' },
      { row: 6, col: 4, blocker: 'wood' },
      { row: 6, col: 5, blocker: 'wood' },
      { row: 4, col: 2, blocker: 'stone' },
      { row: 5, col: 2, blocker: 'stone' },
      { row: 4, col: 7, blocker: 'stone' },
      { row: 5, col: 7, blocker: 'stone' },
    ],
  },

  // ===================== LEVELS 21 - 25: EXPERT+ (SPECIAL BLOCKS & LOCKED) =====================
  {
    id: 21,
    title: 'Bomb Foundry',
    difficulty: 'expert+',
    targetScore: 10500,
    targetLines: 36,
    description: 'Explosive Bomb blocks detonate surrounding 3x3 cells upon line clear!',
    reshuffleLimit: 2,
    starThresholds: [10500, 15000, 20000],
    initialBoard: [
      { row: 4, col: 4, color: 'magenta', special: 'bomb' },
      { row: 5, col: 5, color: 'cyan', special: 'bomb' },
      { row: 3, col: 3, blocker: 'wood' },
      { row: 6, col: 6, blocker: 'wood' },
      { row: 3, col: 6, blocker: 'wood' },
      { row: 6, col: 3, blocker: 'wood' },
    ],
  },
  {
    id: 22,
    title: 'Laser Array',
    difficulty: 'expert+',
    targetScore: 11000,
    targetLines: 38,
    description: 'Horizontal and vertical laser blocks beam across the board when triggered.',
    reshuffleLimit: 2,
    starThresholds: [11000, 15800, 21000],
    initialBoard: [
      { row: 2, col: 5, color: 'yellow', special: 'line_h' },
      { row: 7, col: 4, color: 'green', special: 'line_v' },
      { row: 4, col: 1, blocker: 'ice' },
      { row: 5, col: 8, blocker: 'ice' },
    ],
  },
  {
    id: 23,
    title: 'Locked Vaults',
    difficulty: 'expert+',
    targetScore: 11500,
    targetLines: 40,
    description: 'Locked grid cells cannot be placed upon until neighboring lines trigger unlock.',
    reshuffleLimit: 2,
    starThresholds: [11500, 16500, 22000],
    initialBoard: [
      { row: 4, col: 4, blocker: 'locked' },
      { row: 4, col: 5, blocker: 'locked' },
      { row: 5, col: 4, blocker: 'locked' },
      { row: 5, col: 5, blocker: 'locked' },
      { row: 2, col: 2, color: 'orange' },
      { row: 7, col: 7, color: 'purple' },
    ],
  },
  {
    id: 24,
    title: 'Detonation Ring',
    difficulty: 'expert+',
    targetScore: 12000,
    targetLines: 42,
    description: 'Trigger bomb chains to blast through perimeter ice barricades.',
    reshuffleLimit: 2,
    starThresholds: [12000, 17200, 23000],
    initialBoard: [
      { row: 3, col: 4, color: 'orange', special: 'bomb' },
      { row: 6, col: 5, color: 'cyan', special: 'bomb' },
      { row: 2, col: 3, blocker: 'ice' },
      { row: 2, col: 6, blocker: 'ice' },
      { row: 7, col: 3, blocker: 'ice' },
      { row: 7, col: 6, blocker: 'ice' },
    ],
  },
  {
    id: 25,
    title: 'Quartermaster Matrix',
    difficulty: 'expert+',
    targetScore: 12500,
    targetLines: 44,
    description: 'A symmetrical maze requiring laser sweeps to keep the board viable.',
    reshuffleLimit: 2,
    starThresholds: [12500, 18000, 24000],
    initialBoard: [
      { row: 4, col: 4, color: 'yellow', special: 'line_h' },
      { row: 5, col: 5, color: 'yellow', special: 'line_v' },
      { row: 1, col: 1, blocker: 'wood' },
      { row: 1, col: 8, blocker: 'wood' },
      { row: 8, col: 1, blocker: 'wood' },
      { row: 8, col: 8, blocker: 'wood' },
    ],
  },

  // ===================== LEVELS 26 - 30: EXTREME =====================
  {
    id: 26,
    title: 'The Anvil',
    difficulty: 'extreme',
    targetScore: 13000,
    targetLines: 45,
    description: 'Extreme piece pressure with heavy stone wedges. Only deliberate planning succeeds.',
    reshuffleLimit: 2,
    starThresholds: [13000, 18800, 25000],
    initialBoard: [
      { row: 4, col: 3, blocker: 'stone' },
      { row: 4, col: 4, blocker: 'stone' },
      { row: 4, col: 5, blocker: 'stone' },
      { row: 4, col: 6, blocker: 'stone' },
      { row: 5, col: 4, blocker: 'stone' },
      { row: 5, col: 5, blocker: 'stone' },
    ],
  },
  {
    id: 27,
    title: 'Thermal Fracture',
    difficulty: 'extreme',
    targetScore: 13500,
    targetLines: 48,
    description: 'Eight ice blockers surround central bomb catalysts. Precision line clears needed.',
    reshuffleLimit: 2,
    starThresholds: [13500, 19500, 26000],
    initialBoard: [
      { row: 4, col: 4, color: 'magenta', special: 'bomb' },
      { row: 5, col: 5, color: 'magenta', special: 'bomb' },
      { row: 3, col: 4, blocker: 'ice' },
      { row: 3, col: 5, blocker: 'ice' },
      { row: 6, col: 4, blocker: 'ice' },
      { row: 6, col: 5, blocker: 'ice' },
      { row: 4, col: 3, blocker: 'ice' },
      { row: 5, col: 3, blocker: 'ice' },
      { row: 4, col: 6, blocker: 'ice' },
      { row: 5, col: 6, blocker: 'ice' },
    ],
  },
  {
    id: 28,
    title: 'Valkyrie Lattice',
    difficulty: 'extreme',
    targetScore: 14000,
    targetLines: 50,
    description: 'Dense alternating lattice. Every piece placement requires 2-3 moves of foresight.',
    reshuffleLimit: 2,
    starThresholds: [14000, 20200, 27000],
    initialBoard: [
      { row: 2, col: 2, blocker: 'wood' },
      { row: 2, col: 4, blocker: 'wood' },
      { row: 2, col: 6, blocker: 'wood' },
      { row: 7, col: 2, blocker: 'wood' },
      { row: 7, col: 4, blocker: 'wood' },
      { row: 7, col: 6, blocker: 'wood' },
      { row: 4, col: 7, blocker: 'stone' },
      { row: 5, col: 7, blocker: 'stone' },
    ],
  },
  {
    id: 29,
    title: 'Oblivion Spire',
    difficulty: 'extreme',
    targetScore: 14500,
    targetLines: 52,
    description: 'A tall stone column piercing the center with perimeter wood nodes.',
    reshuffleLimit: 2,
    starThresholds: [14500, 21000, 28000],
    initialBoard: [
      { row: 2, col: 4, blocker: 'stone' },
      { row: 3, col: 4, blocker: 'stone' },
      { row: 6, col: 5, blocker: 'stone' },
      { row: 7, col: 5, blocker: 'stone' },
      { row: 1, col: 1, blocker: 'ice' },
      { row: 1, col: 8, blocker: 'ice' },
      { row: 8, col: 1, blocker: 'ice' },
      { row: 8, col: 8, blocker: 'ice' },
    ],
  },
  {
    id: 30,
    title: 'Titan Siege',
    difficulty: 'extreme',
    targetScore: 15000,
    targetLines: 55,
    description: 'Monumental 15,000 score requirement across a heavily defended 10x10 arena.',
    reshuffleLimit: 2,
    starThresholds: [15000, 21800, 29000],
    initialBoard: [
      { row: 3, col: 3, blocker: 'stone' },
      { row: 3, col: 6, blocker: 'stone' },
      { row: 6, col: 3, blocker: 'stone' },
      { row: 6, col: 6, blocker: 'stone' },
      { row: 2, col: 4, color: 'cyan', special: 'line_h' },
      { row: 7, col: 5, color: 'cyan', special: 'line_v' },
    ],
  },

  // ===================== LEVELS 31 - 35: MASTER =====================
  {
    id: 31,
    title: 'Master Architect',
    difficulty: 'master',
    targetScore: 15500,
    targetLines: 56,
    description: 'Complex polyomino pool requires absolute spatial precision.',
    reshuffleLimit: 2,
    starThresholds: [15500, 22500, 30000],
    initialBoard: [
      { row: 1, col: 2, blocker: 'ice' },
      { row: 1, col: 7, blocker: 'ice' },
      { row: 8, col: 2, blocker: 'ice' },
      { row: 8, col: 7, blocker: 'ice' },
      { row: 4, col: 4, color: 'green', special: 'bomb' },
      { row: 5, col: 5, color: 'orange', special: 'bomb' },
    ],
  },
  {
    id: 32,
    title: 'Labyrinth of Shadows',
    difficulty: 'master',
    targetScore: 16000,
    targetLines: 58,
    description: 'Symmetric stone corridors leave zero margin for clumsy placements.',
    reshuffleLimit: 2,
    starThresholds: [16000, 23200, 31000],
    initialBoard: [
      { row: 2, col: 3, blocker: 'stone' },
      { row: 2, col: 6, blocker: 'stone' },
      { row: 7, col: 3, blocker: 'stone' },
      { row: 7, col: 6, blocker: 'stone' },
      { row: 4, col: 2, blocker: 'locked' },
      { row: 5, col: 7, blocker: 'locked' },
    ],
  },
  {
    id: 33,
    title: 'The Iron Crucible',
    difficulty: 'master',
    targetScore: 16500,
    targetLines: 60,
    description: 'Dual layer perimeter of wood and ice with center locked cells.',
    reshuffleLimit: 2,
    starThresholds: [16500, 24000, 32000],
    initialBoard: [
      { row: 3, col: 3, blocker: 'wood' },
      { row: 3, col: 6, blocker: 'wood' },
      { row: 6, col: 3, blocker: 'ice' },
      { row: 6, col: 6, blocker: 'ice' },
      { row: 4, col: 4, blocker: 'locked' },
      { row: 5, col: 5, blocker: 'locked' },
    ],
  },
  {
    id: 34,
    title: 'Tempest Citadel',
    difficulty: 'master',
    targetScore: 17000,
    targetLines: 62,
    description: 'Laser blocks generated sparingly. Time their detonation for triple line sweeps.',
    reshuffleLimit: 2,
    starThresholds: [17000, 24800, 33000],
    initialBoard: [
      { row: 3, col: 5, color: 'purple', special: 'line_h' },
      { row: 6, col: 4, color: 'purple', special: 'line_v' },
      { row: 1, col: 4, blocker: 'stone' },
      { row: 8, col: 5, blocker: 'stone' },
    ],
  },
  {
    id: 35,
    title: 'Crown of Thorium',
    difficulty: 'master',
    targetScore: 17500,
    targetLines: 64,
    description: 'Master tier challenge. High score target demands continuous combo streaks.',
    reshuffleLimit: 2,
    starThresholds: [17500, 25500, 34000],
    initialBoard: [
      { row: 2, col: 4, blocker: 'ice' },
      { row: 2, col: 5, blocker: 'ice' },
      { row: 7, col: 4, blocker: 'ice' },
      { row: 7, col: 5, blocker: 'ice' },
      { row: 4, col: 2, blocker: 'wood' },
      { row: 5, col: 2, blocker: 'wood' },
      { row: 4, col: 7, blocker: 'wood' },
      { row: 5, col: 7, blocker: 'wood' },
    ],
  },

  // ===================== LEVELS 36 - 39: MASTER+ =====================
  {
    id: 36,
    title: 'Apex Constellation',
    difficulty: 'master+',
    targetScore: 18000,
    targetLines: 66,
    description: 'Constellation layout with minimal safe 3x3 drops. Absolute precision necessary.',
    reshuffleLimit: 2,
    starThresholds: [18000, 26200, 35000],
    initialBoard: [
      { row: 2, col: 2, blocker: 'stone' },
      { row: 2, col: 7, blocker: 'stone' },
      { row: 7, col: 2, blocker: 'stone' },
      { row: 7, col: 7, blocker: 'stone' },
      { row: 4, col: 4, blocker: 'ice' },
      { row: 5, col: 5, blocker: 'ice' },
    ],
  },
  {
    id: 37,
    title: 'The Abyssal Ring',
    difficulty: 'master+',
    targetScore: 18500,
    targetLines: 68,
    description: 'An expansive ring of frozen obstacles enclosing two volatile bomb units.',
    reshuffleLimit: 2,
    starThresholds: [18500, 27000, 36000],
    initialBoard: [
      { row: 3, col: 3, blocker: 'ice' },
      { row: 3, col: 6, blocker: 'ice' },
      { row: 6, col: 3, blocker: 'ice' },
      { row: 6, col: 6, blocker: 'ice' },
      { row: 4, col: 5, color: 'cyan', special: 'bomb' },
      { row: 5, col: 4, color: 'orange', special: 'bomb' },
    ],
  },
  {
    id: 38,
    title: 'Cataclysmic Array',
    difficulty: 'master+',
    targetScore: 19000,
    targetLines: 70,
    description: 'Locked sectors and granite pillars restrict polyomino flexibility.',
    reshuffleLimit: 2,
    starThresholds: [19000, 27800, 37000],
    initialBoard: [
      { row: 3, col: 4, blocker: 'locked' },
      { row: 3, col: 5, blocker: 'locked' },
      { row: 6, col: 4, blocker: 'locked' },
      { row: 6, col: 5, blocker: 'locked' },
      { row: 4, col: 2, blocker: 'stone' },
      { row: 5, col: 7, blocker: 'stone' },
    ],
  },
  {
    id: 39,
    title: 'Penultimate Crucible',
    difficulty: 'master+',
    targetScore: 19500,
    targetLines: 72,
    description: 'The final gate before Level 40. High density board with intense tactical depth.',
    reshuffleLimit: 2,
    starThresholds: [19500, 28500, 38000],
    initialBoard: [
      { row: 2, col: 3, blocker: 'wood' },
      { row: 2, col: 6, blocker: 'wood' },
      { row: 7, col: 3, blocker: 'ice' },
      { row: 7, col: 6, blocker: 'ice' },
      { row: 4, col: 4, color: 'yellow', special: 'line_h' },
      { row: 5, col: 5, color: 'yellow', special: 'line_v' },
    ],
  },

  // ===================== LEVEL 40: MASTER+ FINAL GRAND CHALLENGE =====================
  {
    id: 40,
    title: 'Grandmaster Pinnacle',
    difficulty: 'master+',
    targetScore: 20000,
    targetLines: 75,
    description: 'The ultimate 10x10 challenge! Complex blockers, bombs, and massive 20,000 score threshold.',
    reshuffleLimit: 2,
    starThresholds: [20000, 29500, 40000],
    initialBoard: [
      { row: 2, col: 2, blocker: 'stone' },
      { row: 2, col: 7, blocker: 'stone' },
      { row: 7, col: 2, blocker: 'stone' },
      { row: 7, col: 7, blocker: 'stone' },
      { row: 4, col: 3, blocker: 'ice' },
      { row: 4, col: 6, blocker: 'ice' },
      { row: 5, col: 3, blocker: 'ice' },
      { row: 5, col: 6, blocker: 'ice' },
      { row: 3, col: 4, color: 'magenta', special: 'bomb' },
      { row: 6, col: 5, color: 'cyan', special: 'bomb' },
      { row: 4, col: 5, color: 'yellow', special: 'line_h' },
      { row: 5, col: 4, color: 'yellow', special: 'line_v' },
    ],
  },
];
