/**
 * SOCCER PING PONG - 20 Progressive Levels Configuration
 * Deterministic, Non-Random Difficulty Progression with Multiple Independent Constraints:
 * - Target score & Minimum rally requirement
 * - Carried Cumulative Score required to unlock
 * - Progressive ball speed & acceleration
 * - AI reaction delay, lateral speed & intercept accuracy
 * - Opponent wing-targeting bias (Left Wing, Center, Right Wing)
 * - Timing window for sweet-spot hits
 * - Mistakes allowed (lives)
 */

import { SoccerLevelConfig } from './types';

const RAW_SOCCER_LEVELS: Omit<SoccerLevelConfig, 'targetGoals'>[] = [
  // =========================================================================
  // TIER 1: TRAINING COMPLEX (Levels 1–3) - Grassroots Turf, Daytime
  // Controlled difficulty: accessible but requires positioning and timing.
  // =========================================================================
  {
    level: 1,
    title: 'First Touch Kickoff',
    subtitle: 'Grassroots Pitch • Daylight',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Ground',
    difficultyTier: 'Moderate',
    difficultyStars: 1,
    targetScore: 1000,
    targetRally: 5,
    targetPerfectHits: 1,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.05,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.58,
    opponentSpeed: 3.2,
    spinFactor: 0.06,
    timingWindow: 0.28,
    livesAllowed: 3,
    requiredCumulativeScore: 0, // Unlocked by default
    aiAttackDirectionBias: 0.35,
    aiReactionDelay: 0.12,
    specialRule: 'Swipe to defend left/right wings. Time your kick when ball reaches your strike zone.',
    specialBallType: 'NONE',
    description: 'Reposition across the full width to intercept wing shots. Mindless kick spam will whiff!',
  },
  {
    level: 2,
    title: 'Rhythm & Return',
    subtitle: 'Grassroots Pitch • Morning Sun',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Ground',
    difficultyTier: 'Moderate',
    difficultyStars: 1,
    targetScore: 1600,
    targetRally: 6,
    targetPerfectHits: 2,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.12,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.62,
    opponentSpeed: 3.5,
    spinFactor: 0.08,
    timingWindow: 0.26,
    livesAllowed: 3,
    requiredCumulativeScore: 1000,
    aiAttackDirectionBias: 0.42,
    aiReactionDelay: 0.10,
    specialRule: 'AI begins varying wing attacks. Reposition smoothly between returns to defend your goal.',
    specialBallType: 'NONE',
    description: 'Score increases with return quality and rally length. Aim for sweet-spot timing!',
  },
  {
    level: 3,
    title: 'Placement Control',
    subtitle: 'Grassroots Pitch • Midday Sun',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Ground',
    difficultyTier: 'Moderate',
    difficultyStars: 2,
    targetScore: 2400,
    targetRally: 7,
    targetPerfectHits: 2,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.18,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.66,
    opponentSpeed: 3.8,
    spinFactor: 0.10,
    timingWindow: 0.24,
    livesAllowed: 3,
    requiredCumulativeScore: 2600,
    aiAttackDirectionBias: 0.48,
    aiReactionDelay: 0.09,
    specialRule: 'Precision ball introduced! Strike at paddle center to direct fast shots past the AI.',
    specialBallType: 'PRECISION',
    description: 'Defend both wings actively. If the computer breaches your wing defense, it will score.',
  },

  // =========================================================================
  // TIER 2: CITY ARENA (Levels 4–6) - Evening Dusk, Faster Ball & Aggressive AI
  // =========================================================================
  {
    level: 4,
    title: 'City Sunset Clash',
    subtitle: 'Metropolitan Court • Golden Hour',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Arena',
    difficultyTier: 'Challenging',
    difficultyStars: 2,
    targetScore: 3200,
    targetRally: 8,
    targetPerfectHits: 3,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.25,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.70,
    opponentSpeed: 4.2,
    spinFactor: 0.14,
    timingWindow: 0.22,
    livesAllowed: 3,
    requiredCumulativeScore: 5000,
    aiAttackDirectionBias: 0.54,
    aiReactionDelay: 0.08,
    specialRule: 'Faster baseline velocity. Opponent targets opposite corners with aggressive angles.',
    specialBallType: 'NONE',
    description: 'Use swipe gestures across the pitch to intercept sharp crosscourt drives.',
  },
  {
    level: 5,
    title: 'Power Volley Duel',
    subtitle: 'Metropolitan Court • Dusk Floodlights',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Arena',
    difficultyTier: 'Challenging',
    difficultyStars: 3,
    targetScore: 4000,
    targetRally: 9,
    targetPerfectHits: 3,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.30,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.73,
    opponentSpeed: 4.5,
    spinFactor: 0.17,
    timingWindow: 0.21,
    livesAllowed: 3,
    requiredCumulativeScore: 8200,
    aiAttackDirectionBias: 0.58,
    aiReactionDelay: 0.07,
    specialRule: 'POWER BALL active! Power strikes rocket across the turf with boosted point values.',
    specialBallType: 'POWER',
    description: 'Time your KICK when the ball is right in front of your platform for maximum power.',
  },
  {
    level: 6,
    title: 'Reflex Baseline',
    subtitle: 'Metropolitan Court • Twilight Lights',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Arena',
    difficultyTier: 'Challenging',
    difficultyStars: 3,
    targetScore: 4800,
    targetRally: 10,
    targetPerfectHits: 4,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.36,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.76,
    opponentSpeed: 4.8,
    spinFactor: 0.20,
    timingWindow: 0.20,
    livesAllowed: 3,
    requiredCumulativeScore: 12200,
    aiAttackDirectionBias: 0.62,
    aiReactionDelay: 0.06,
    specialRule: 'Narrower hit window. Maintain positional balance across left, center, and right wings.',
    specialBallType: 'BONUS',
    description: 'Bonus ball awards instant multiplier surge when returned with perfect accuracy!',
  },

  // =========================================================================
  // TIER 3: NATIONAL STADIUM (Levels 7–10) - Ball Angles, Spin, Strict Lives
  // =========================================================================
  {
    level: 7,
    title: 'Curving Crosscourt',
    subtitle: 'National Stadium • Night Match',
    stadiumTier: 'national',
    stadiumName: 'National Grand Complex',
    difficultyTier: 'Advanced',
    difficultyStars: 3,
    targetScore: 5800,
    targetRally: 11,
    targetPerfectHits: 4,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.42,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.79,
    opponentSpeed: 5.1,
    spinFactor: 0.25,
    timingWindow: 0.19,
    livesAllowed: 2,
    requiredCumulativeScore: 17000,
    aiAttackDirectionBias: 0.66,
    aiReactionDelay: 0.05,
    specialRule: 'LIVES REDUCED TO 2. Spin ball curves in mid-flight toward opposite touchlines.',
    specialBallType: 'SPIN',
    description: 'National championship intensity. The AI cuts off loose returns with high accuracy.',
  },
  {
    level: 8,
    title: 'Angular Pressure',
    subtitle: 'National Stadium • Roaring Stands',
    stadiumTier: 'national',
    stadiumName: 'National Grand Complex',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 6800,
    targetRally: 12,
    targetPerfectHits: 5,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.48,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.82,
    opponentSpeed: 5.4,
    spinFactor: 0.28,
    timingWindow: 0.18,
    livesAllowed: 2,
    requiredCumulativeScore: 22800,
    aiAttackDirectionBias: 0.70,
    aiReactionDelay: 0.04,
    specialRule: 'Opponent counters power shots with sharp angled returns into open wings.',
    specialBallType: 'POWER',
    description: 'React immediately to horizontal deflection to protect your wings.',
  },
  {
    level: 9,
    title: 'Tactical Deception',
    subtitle: 'National Stadium • Full Floodlights',
    stadiumTier: 'national',
    stadiumName: 'National Grand Complex',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 8000,
    targetRally: 13,
    targetPerfectHits: 5,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.54,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.84,
    opponentSpeed: 5.7,
    spinFactor: 0.30,
    timingWindow: 0.17,
    livesAllowed: 2,
    requiredCumulativeScore: 29600,
    aiAttackDirectionBias: 0.74,
    aiReactionDelay: 0.03,
    specialRule: 'Rapid pace. AI actively reads player positioning to exploit defensive gaps.',
    specialBallType: 'PRECISION',
    description: 'Swipe fluidly across the field. Standing in the center will leave wings undefended.',
  },
  {
    level: 10,
    title: 'National Cup Qualifier',
    subtitle: 'National Stadium • Championship Night',
    stadiumTier: 'national',
    stadiumName: 'National Grand Complex',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 9500,
    targetRally: 14,
    targetPerfectHits: 6,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.60,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.86,
    opponentSpeed: 6.0,
    spinFactor: 0.32,
    timingWindow: 0.17,
    livesAllowed: 2,
    requiredCumulativeScore: 37600,
    aiAttackDirectionBias: 0.76,
    aiReactionDelay: 0.03,
    specialRule: '14-hit rally requirement to qualify for the Elite International Arena.',
    specialBallType: 'BONUS',
    description: 'A major benchmark test. Consecutive perfect returns required to meet target score.',
  },

  // =========================================================================
  // TIER 4: ELITE ARENA (Levels 11–15) - Very Fast Rallies, Advanced AI
  // =========================================================================
  {
    level: 11,
    title: 'Continental Clash',
    subtitle: 'Elite Stadium • Continental Derby',
    stadiumTier: 'elite',
    stadiumName: 'Continental Elite Arena',
    difficultyTier: 'Expert',
    difficultyStars: 4,
    targetScore: 11000,
    targetRally: 15,
    targetPerfectHits: 6,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.66,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.88,
    opponentSpeed: 6.3,
    spinFactor: 0.35,
    timingWindow: 0.16,
    livesAllowed: 2,
    requiredCumulativeScore: 47100,
    aiAttackDirectionBias: 0.80,
    aiReactionDelay: 0.02,
    specialRule: 'Elite AI reaction. Opponent intercepts wide shots and returns with heavy spin.',
    specialBallType: 'SPIN',
    description: 'Speed accelerates with every consecutive return in the rally.',
  },
  {
    level: 12,
    title: 'High-Altitude Tempest',
    subtitle: 'Elite Stadium • High Atmosphere',
    stadiumTier: 'elite',
    stadiumName: 'Continental Elite Arena',
    difficultyTier: 'Expert',
    difficultyStars: 4,
    targetScore: 12800,
    targetRally: 16,
    targetPerfectHits: 7,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.72,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.90,
    opponentSpeed: 6.6,
    spinFactor: 0.37,
    timingWindow: 0.15,
    livesAllowed: 2,
    requiredCumulativeScore: 58100,
    aiAttackDirectionBias: 0.82,
    aiReactionDelay: 0.02,
    specialRule: 'Ball rebound off touchlines gains +10% velocity boost.',
    specialBallType: 'POWER',
    description: 'Anticipate wall bounces early and position your platform before arrival.',
  },
  {
    level: 13,
    title: 'The Steel Net',
    subtitle: 'Elite Stadium • Spotlight Arena',
    stadiumTier: 'elite',
    stadiumName: 'Continental Elite Arena',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 14800,
    targetRally: 17,
    targetPerfectHits: 7,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.78,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.91,
    opponentSpeed: 6.9,
    spinFactor: 0.39,
    timingWindow: 0.15,
    livesAllowed: 2,
    requiredCumulativeScore: 70900,
    aiAttackDirectionBias: 0.85,
    aiReactionDelay: 0.01,
    specialRule: 'Strict timing window. Off-center contact reduces return trajectory angle.',
    specialBallType: 'PRECISION',
    description: 'Opponent covers 91% of court area. Win by out-rallying with high-speed power kicks.',
  },
  {
    level: 14,
    title: 'Lightning Volley',
    subtitle: 'Elite Stadium • Electric Atmosphere',
    stadiumTier: 'elite',
    stadiumName: 'Continental Elite Arena',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 17000,
    targetRally: 18,
    targetPerfectHits: 8,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.84,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.93,
    opponentSpeed: 7.2,
    spinFactor: 0.41,
    timingWindow: 0.14,
    livesAllowed: 2,
    requiredCumulativeScore: 85700,
    aiAttackDirectionBias: 0.88,
    aiReactionDelay: 0.01,
    specialRule: 'EXTREME BALL SPEED. Ultra-fast reflexes required for touchline saves.',
    specialBallType: 'POWER',
    description: 'Swipe rapidly from touchline to touchline to stay in the point.',
  },
  {
    level: 15,
    title: 'Crown Semifinal',
    subtitle: 'Elite Stadium • Golden Showcase',
    stadiumTier: 'elite',
    stadiumName: 'Continental Elite Arena',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 19500,
    targetRally: 19,
    targetPerfectHits: 8,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.90,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.94,
    opponentSpeed: 7.5,
    spinFactor: 0.43,
    timingWindow: 0.14,
    livesAllowed: 2,
    requiredCumulativeScore: 102700,
    aiAttackDirectionBias: 0.90,
    aiReactionDelay: 0.0,
    specialRule: '19-hit rally benchmark to punch your ticket to the World Grand Finals.',
    specialBallType: 'BONUS',
    description: 'Peak expert competition. Sustained focus under relentless wing pressure.',
  },

  // =========================================================================
  // TIER 5: WORLD CHAMPIONSHIP GRAND STADIUM (Levels 16–20) - Master Arena
  // =========================================================================
  {
    level: 16,
    title: 'World Grand Open',
    subtitle: 'Grand Stadium • Golden Floodlights',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 22500,
    targetRally: 20,
    targetPerfectHits: 9,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.96,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.95,
    opponentSpeed: 7.8,
    spinFactor: 0.45,
    timingWindow: 0.13,
    livesAllowed: 2,
    requiredCumulativeScore: 122200,
    aiAttackDirectionBias: 0.92,
    aiReactionDelay: 0.0,
    specialRule: 'MASTER OPPONENT. AI targets unpredicted angles and executes instant returns.',
    specialBallType: 'SPIN',
    description: 'The world grand stage. Only elite players with mastery of swipe defense can survive.',
  },
  {
    level: 17,
    title: 'The Golden Arc',
    subtitle: 'Grand Stadium • Midnight Finale',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 26000,
    targetRally: 22,
    targetPerfectHits: 10,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.02,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.96,
    opponentSpeed: 8.1,
    spinFactor: 0.47,
    timingWindow: 0.12,
    livesAllowed: 2,
    requiredCumulativeScore: 144700,
    aiAttackDirectionBias: 0.93,
    aiReactionDelay: 0.0,
    specialRule: 'Double spin physics active. The ball cuts sharply across the green turf.',
    specialBallType: 'SPIN',
    description: 'Precision timing is mandatory. Contact outside the sweet spot risks an immediate concession.',
  },
  {
    level: 18,
    title: 'Stratosphere Pressure',
    subtitle: 'Grand Stadium • Golden Confetti',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 30000,
    targetRally: 24,
    targetPerfectHits: 11,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.08,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.97,
    opponentSpeed: 8.4,
    spinFactor: 0.48,
    timingWindow: 0.12,
    livesAllowed: 2,
    requiredCumulativeScore: 170700,
    aiAttackDirectionBias: 0.94,
    aiReactionDelay: 0.0,
    specialRule: 'Score multiplier cap raised to x2.5 for players sustaining high combos.',
    specialBallType: 'POWER',
    description: 'Every defensive save earns premium points. Maintain continuous rally momentum.',
  },
  {
    level: 19,
    title: 'Champion’s Gauntlet',
    subtitle: 'Grand Stadium • Roar of 100,000',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 35000,
    targetRally: 26,
    targetPerfectHits: 12,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.14,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.98,
    opponentSpeed: 8.7,
    spinFactor: 0.50,
    timingWindow: 0.11,
    livesAllowed: 1,
    requiredCumulativeScore: 200700,
    aiAttackDirectionBias: 0.95,
    aiReactionDelay: 0.0,
    specialRule: 'SUDDEN DEATH: 1 LIFE ONLY. A single missed defensive save ends the match.',
    specialBallType: 'BONUS',
    description: 'The ultimate test of nerves and defensive coverage across the entire pitch.',
  },
  {
    level: 20,
    title: 'Grand Master Finale',
    subtitle: 'Grand Stadium • World Trophy Gold',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 42000,
    targetRally: 30,
    targetPerfectHits: 14,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.20,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.99,
    opponentSpeed: 9.0,
    spinFactor: 0.52,
    timingWindow: 0.10,
    livesAllowed: 1,
    requiredCumulativeScore: 235700,
    aiAttackDirectionBias: 0.96,
    aiReactionDelay: 0.0,
    specialRule: '30-RALLY WORLD RECORD. The pinnacle of Soccer Ping-Pong speed, skill, and precision.',
    specialBallType: 'POWER',
    description: 'Defeat the world master AI to lift the Golden Football Trophy and achieve legendary status.',
  },
];

export const SOCCER_LEVELS: SoccerLevelConfig[] = RAW_SOCCER_LEVELS.map((lvl) => ({
  ...lvl,
  targetGoals: lvl.level <= 5 ? 3 : lvl.level <= 12 ? 4 : 5,
}));
